name: gpt-story
channels:
    - defaults
    - anaconda
    - conda-forge
dependencies:
    - python=3.12.1
    - tqdm
    - pip
    - pyparsing
    - pydub
    - pandas
    - pip:
        - openai
        - elevenlabs
        - playsound